version: '3'

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - ./api/.env

  postgres:
    image: postgres:11.4
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=mobile
      - POSTGRES_USER=mobile
      - POSTGRES_PASSWORD=mobile

  ngrok:
    image: wernight/ngrok
    ports:
      - "4242:4242"
    command:
      - /bin/sh
      - -c
      - |
        ngrok http api:3000
    volumes:
      - .:/home/ngrok/.ngrok2/
    depends_on:
      - api
